# >> Preferred themes
theme: jekyll-theme-hacker
# theme: jekyll-theme-slate
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-primer

# >> I don't like these themes.
# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-merlot
# theme: jekyll-theme-minimal
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine
